#! /bin/sh

# ___.
# \_ |__    ____________ __  _  __ _____ _______   ____
#  | __ \  /  ___/\____ \\ \/ \/ //     \\_  __ \_/ ___\
#  | \_\ \ \___ \ |  |_> >\     /|  Y Y  \|  | \/\  \___
#  |___  //____  >|   __/  \/\_/ |__|_|  /|__|    \___  >
#      \/      \/ |__|                 \/             \/


sxhkd &
xrdb merge ~/.Xresources &
~/.config/polybar/bar.sh &
compton &
nm-applet &
sh .fehbg &

#bspc monitor -d I II III IV V
bspc monitor -d '' '' '' '' '' ''

bspc config border_width         2
bspc config window_gap          30
bspc config bottom_padding 30
bspc config top_padding 30
bspc config left_padding 50
bspc config right_padding 50

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer   true
bspc config normal_border_color "#2f343f"
bspc config focused_border_color "#e7e8eb"
bspc config active_border_color "#788249"
bspc config presel_feedback_color "#788249"

bspc rule -a Gnome-terminal state=floating follow=on
bspc rule -a Termite state=floating follow=on
bspc rule -a Gedit state=floating follow=on
bspc rule -a Firefox state=floating follow=on
bspc rule -a Pcmanfm state=floating follow=on
bspc rule -a URxvt state=floating follow=on
bspc rule -a Audacious state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Sublime_text state=floating follow=on
bspc rule -a TelegramDesktop state=floating follow=on
bspc rule -a Conky manage=off
